#!/bin/bash -e
#
# restore-stock-android.sh — Restore a UZ801 dongle to factory Stock Android.
#
# Strategy: parse the rawprogram0.xml from a complete Stock Android EDL dump
# and write each partition image directly to its absolute start_sector via
# `edl ws`. This bypasses the partition-name lookup (which only works on the
# CURRENT GPT) — useful when the device currently has an OpenStick GPT and
# we need to overwrite eMMC layout entirely with Stock Android's GPT first.
#
# Order of operations:
#   1. Flash universal Stock Android partitions sector-by-sector (boot chain
#      + Android system + modem) from <stock-dir>/rawprogram0.xml
#   2. Override modem-calibration partitions (modemst1/2/fsg/sec/fsc) with
#      THIS unit's per-IMEI backup so the dongle keeps its own IMEI/cal
#   3. Reset
#
# Sources combined:
#   <stock-dir>     — universal Stock Android UZ801 image dump (with
#                     rawprogram0.xml). Hardware-generic except modem cal.
#   <imei-cal-dir>  — this device's per-IMEI modem calibration backup
#                     (modemst1.bin, modemst2.bin, fsg.bin, sec.bin, fsc.bin)
#
# Usage:
#   bash restore-stock-android.sh <stock-dir> <imei-cal-dir>
# Example:
#   bash restore-stock-android.sh \
#       backup/partitions \
#       backup/stock_uz801_860018046136249_20260417
#
# Prerequisites:
#   - Dongle in EDL mode (USB ID 05c6:9008). For UZ801 reach EDL by either:
#     * shorting USB D+ to GND while plugging in (forces PBL EDL fallback)
#     * or `adb reboot edl` from Stock Android (only if Stock is still on it)
#     The reset pin alone reaches lk1st-fastboot, NOT EDL.
#   - edlclient installed: pipx install git+https://github.com/bkerler/edl.git
#   - --memory=emmc is mandatory on UZ801 to avoid USB-Overflow on writes.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# pipx-installed binaries are in ~/.local/bin which non-interactive shells
# don't inherit. Add it eagerly so `edl` resolves.
export PATH="$HOME/.local/bin:$PATH"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()  { echo -e "${GREEN}[+]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[x]${NC} $1"; exit 1; }

which edl >/dev/null 2>&1 || err "edl not in PATH (looked in: $PATH)."

STOCK_DIR="${1:-}"
CAL_DIR="${2:-}"
[ -n "$STOCK_DIR" ] && [ -n "$CAL_DIR" ] \
    || err "Usage: bash restore-stock-android.sh <stock-dir> <imei-cal-dir>"
[ -d "$STOCK_DIR" ] || err "Stock directory not found: $STOCK_DIR"
[ -d "$CAL_DIR" ]   || err "Calibration directory not found: $CAL_DIR"

XML="$STOCK_DIR/rawprogram0.xml"
[ -f "$XML" ] || err "rawprogram0.xml not found in $STOCK_DIR"

# Resolve to absolute paths so cd-ing later still works
STOCK_DIR="$(cd "$STOCK_DIR" && pwd)"
CAL_DIR="$(cd "$CAL_DIR" && pwd)"
XML="$STOCK_DIR/rawprogram0.xml"

EDL_OPTS=(--memory=emmc)

# Explicit Firehose loader — without this, edl auto-detects but the auto-
# detected loader on UZ801 hangs Sahara on `ws` writes (observed
# 2026-04-23 during SIM-WIN-14 restore: 14 min timeout on sector-based
# write of modem.bin). The longcheer 007050e1 fhprg_peek.bin matches the
# UZ801 / MSM8916 HWID family and works reliably.
LOADER_CANDIDATE="$HOME/.local/share/pipx/venvs/edlclient/lib/python3.13/site-packages/Loaders/longcheer/007050e100000000_3022817d373fd7f9_fhprg_peek.bin"
if [ -f "$LOADER_CANDIDATE" ]; then
    EDL_OPTS+=(--loader="$LOADER_CANDIDATE")
fi

# Skip these labels in Phase 1:
#   - userdata: 2.5 GB, Android initializes on first boot anyway
#   - BackupGPT: start_sector is "NUM_DISK_SECTORS-33." (placeholder), needs
#     dynamic compute. PrimaryGPT alone is enough for normal boot — backup
#     GPT is regenerated by firmware/sbl on first boot if primary is intact.
#   - DDR: not a writable flash partition
# PrimaryGPT (sector 0) IS flashed — without it the partition table still
# describes OpenStick's layout, which doesn't match the physical content
# we just wrote.
SKIP_LABELS_RE='^(userdata|BackupGPT|DDR)$'

# Modem calibration partitions — these come from the IMEI cal dir, not stock.
CAL_LABELS_RE='^(modemst1|modemst2|fsg|sec|fsc)$'

# Parse rawprogram0.xml entries. Each <program …/> tag is on a single line in
# this XML. Extract: filename, label, start_sector. Output one entry per line
# as: <label>|<filename>|<start_sector>
PLAN_FILE=$(mktemp)
trap 'rm -f "$PLAN_FILE"' EXIT
grep -E '<program ' "$XML" | while read -r line; do
    label=$(echo "$line"     | grep -oE 'label="[^"]+"'         | cut -d'"' -f2)
    fname=$(echo "$line"     | grep -oE 'filename="[^"]+"'      | cut -d'"' -f2)
    sector=$(echo "$line"    | grep -oE 'start_sector="[^"]+"'  | cut -d'"' -f2)
    [ -z "$label" ] && continue
    [ -z "$fname" ] && continue
    echo "$label|$fname|$sector"
done > "$PLAN_FILE"

# ─── Show plan ──────────────────────────────────────────────────────────────
log "Restore plan from XML: $XML"
log "  Stock images:   $STOCK_DIR"
log "  IMEI cal:       $CAL_DIR"
echo ""
log "  Phase 1 (universal Stock Android per rawprogram0.xml):"
printf "  %-12s %-15s %-12s %s\n" "LABEL" "FILE" "SECTOR" "ACTION"
printf "  %-12s %-15s %-12s %s\n" "-----" "----" "------" "------"

PHASE1_PLAN=()
while IFS='|' read -r label fname sector; do
    fpath="$STOCK_DIR/$fname"
    if echo "$label" | grep -qE "$SKIP_LABELS_RE"; then
        printf "  %-12s %-15s %-12s SKIP (excluded)\n" "$label" "$fname" "$sector"
        continue
    fi
    if echo "$label" | grep -qE "$CAL_LABELS_RE"; then
        printf "  %-12s %-15s %-12s SKIP (will use cal-dir in Phase 2)\n" "$label" "$fname" "$sector"
        continue
    fi
    if [ ! -f "$fpath" ]; then
        printf "  %-12s %-15s %-12s SKIP (file missing)\n" "$label" "$fname" "$sector"
        continue
    fi
    sz=$(du -h "$fpath" | cut -f1)
    printf "  %-12s %-15s %-12s %s\n" "$label" "$fname" "$sector" "ws @$sector ($sz)"
    PHASE1_PLAN+=("$label|$fpath|$sector")
done < "$PLAN_FILE"

echo ""
log "  Phase 2 (per-IMEI modem calibration overrides):"
PHASE2_PLAN=()
for label in modemst1 modemst2 fsg sec fsc; do
    cpath="$CAL_DIR/${label}.bin"
    sector=$(awk -F'|' -v l="$label" '$1==l{print $3}' "$PLAN_FILE")
    if [ ! -f "$cpath" ]; then
        printf "  %-12s %-15s %-12s SKIP (file missing in cal-dir)\n" "$label" "${label}.bin" "$sector"
        continue
    fi
    sz=$(du -h "$cpath" | cut -f1)
    printf "  %-12s %-15s %-12s ws @$sector ($sz)\n" "$label" "${label}.bin" "$sector"
    PHASE2_PLAN+=("$label|$cpath|$sector")
done

echo ""
log "  Total Phase 1: ${#PHASE1_PLAN[@]} writes"
log "  Total Phase 2: ${#PHASE2_PLAN[@]} writes"

# IMEI banner
IMEI=""
[ -f "$CAL_DIR/device_info.txt" ] && IMEI=$(awk -F': ' '/^IMEI:/{print $2; exit}' "$CAL_DIR/device_info.txt")
[ -n "$IMEI" ] && log "  Target IMEI: $IMEI"

# ─── Confirmation ────────────────────────────────────────────────────────────
echo ""
warn "DESTRUCTIVE: this overwrites the dongle's eMMC with Stock Android."
warn "Userdata is not flashed (Android initializes on first boot)."
if [ "${YES:-0}" != "1" ]; then
    echo -ne "${YELLOW}[!]${NC} Continue? [y/N] "
    read -r CONTINUE
    [ "$CONTINUE" = "y" ] || [ "$CONTINUE" = "Y" ] || err "Aborted by user."
fi

# ─── EDL detection ───────────────────────────────────────────────────────────
log "Checking for EDL device..."
for i in $(seq 1 30); do
    lsusb 2>/dev/null | grep -q "05c6:9008" && break
    if [ "$i" = 1 ]; then
        warn "Device not in EDL mode."
        warn "  UZ801: short USB D+ to GND while plugging in"
        warn "  (reset pin alone goes to lk1st-fastboot, not EDL)"
    fi
    [ $((i % 3)) = 0 ] && echo "  waiting... (${i}/30)"
    sleep 2
done
lsusb 2>/dev/null | grep -q "05c6:9008" || err "EDL device not detected after 60s."
log "EDL device detected."

# ─── Phase 1: Universal Stock Android ────────────────────────────────────────
log "=== Phase 1: Stock Android sector writes ==="
FAILED=0
DONE=0
for entry in "${PHASE1_PLAN[@]}"; do
    IFS='|' read -r label fpath sector <<< "$entry"
    log "  → $label @sector $sector ($(du -h "$fpath" | cut -f1))"
    edl_out=$(edl "${EDL_OPTS[@]}" ws "$sector" "$fpath" 2>&1) ; edl_rc=$?
    echo "$edl_out" | tail -3
    if [ "$edl_rc" -ne 0 ] || echo "$edl_out" | grep -qiE 'error|fail|exception|traceback'; then
        warn "    write of $label FAILED (rc=$edl_rc)"
        FAILED=$((FAILED + 1))
    else
        DONE=$((DONE + 1))
    fi
done
log "Phase 1 done: $DONE OK, $FAILED FAILED"

# ─── Phase 2: Per-IMEI modem calibration ─────────────────────────────────────
log "=== Phase 2: per-IMEI modem calibration ==="
for entry in "${PHASE2_PLAN[@]}"; do
    IFS='|' read -r label fpath sector <<< "$entry"
    log "  → $label @sector $sector ($(du -h "$fpath" | cut -f1))"
    edl_out=$(edl "${EDL_OPTS[@]}" ws "$sector" "$fpath" 2>&1) ; edl_rc=$?
    echo "$edl_out" | tail -3
    if [ "$edl_rc" -ne 0 ] || echo "$edl_out" | grep -qiE 'error|fail|exception|traceback'; then
        warn "    write of $label FAILED (rc=$edl_rc)"
        FAILED=$((FAILED + 1))
    else
        DONE=$((DONE + 1))
    fi
done

# ─── Reset ───────────────────────────────────────────────────────────────────
log "Resetting device..."
edl "${EDL_OPTS[@]}" reset 2>&1 | tail -3 || true

echo ""
if [ "$FAILED" -gt 0 ]; then
    warn "═══════════════════════════════════════"
    warn "  Restore completed with $FAILED FAILURES (of $((DONE + FAILED)) writes)"
    warn "  Re-run from EDL if device doesn't boot — sector writes are idempotent."
    warn "═══════════════════════════════════════"
    exit 1
else
    log "═══════════════════════════════════════"
    log "  Restore complete: $DONE writes successful, 0 failures."
    log "  Next: unplug + replug. Wait ~30 s for Android first-boot init."
    log "  Verify with: lsusb (expect 05c6:f00e Stock Android)"
    log "═══════════════════════════════════════"
fi
